### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by stamourv** [kanso37/dssl2_vscode_extension#1]
Hey! This looks pretty cool.
What's the current status of the project? Would you say it's suitable for general use?

**Comment by kanso37** [comment]
Oh wow! Hello! To be honest I am not actively maintaining this, but it seems to still work pretty well. I didn't make this originally with the purpose of making it an official extension, but I am happy of course for anyone to use it! It's very hacked together (e.g., with some regex from the Python highlighting extension), so I'm not sure whether it meets the quality level suitable for general use. (I think you might be a better judge of this than me.) If you want to, I would totally be happy to add you as a collaborator. I don't mind if it is changed in any way.

**Comment by stamourv** [comment]
Cool.
I don't actually know the first thing about vscode, so I don't expect to make changes to it.
I was more thinking of pointing my students to your plugin if they were already vscode users.
If I do, I'd like to credit you of course. Do you prefer to use your username or your real name (which I don't know)?

**Comment by kanso37** [comment]
Just my username is fine, although I don't even mind if you don't mention it at all and just give them the link to the repository. Thanks!

**Comment by stamourv** [comment]
Sounds good, thanks!
